// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'allIssues': string;
  'info': string;
  'issue': string;
  'issueType': string;
  'issues': string;
  'missingWanted': string;
}
export const cssExports: CssExports;
export default cssExports;
