// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'issueCount': string;
  'monitored': string;
  'sortName': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
