// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addForm': string;
  'addLink': string;
  'chip': string;
  'chipLink': string;
  'chipRemove': string;
  'chipType': string;
  'error': string;
  'label': string;
  'relations': string;
  'select': string;
}
export const cssExports: CssExports;
export default cssExports;
