// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'control': string;
  'controls': string;
  'empty': string;
  'error': string;
  'exact': string;
  'existingRow': string;
  'folder': string;
  'probable': string;
  'queuedMessage': string;
  'select': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
