// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionButton': string;
  'actionMenuIcon': string;
  'actions': string;
  'actionsMenu': string;
  'actionsMenuContent': string;
  'collapseButtonContainer': string;
  'collapseButtonIcon': string;
  'expandButton': string;
  'expandButtonIcon': string;
  'header': string;
  'issueCount': string;
  'issueCountTooltip': string;
  'issueType': string;
  'issueTypeLabel': string;
  'issues': string;
  'left': string;
  'noIssues': string;
}
export const cssExports: CssExports;
export default cssExports;
