// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'control': string;
  'controls': string;
  'empty': string;
  'error': string;
  'exact': string;
  'folder': string;
  'folderRow': string;
  'imported': string;
  'pathInput': string;
  'probable': string;
  'progress': string;
  'progressMessage': string;
  'rejected': string;
  'reportSummary': string;
  'select': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
