// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'container': string;
  'disambiguation': string;
  'expandButton': string;
  'header': string;
  'info': string;
  'issueCount': string;
  'issueType': string;
  'issueTypeLabel': string;
  'left': string;
  'modalFooter': string;
  'name': string;
  'overview': string;
  'poster': string;
  'searchForNewIssueContainer': string;
  'searchForNewIssueInput': string;
  'searchForNewIssueLabel': string;
  'searchForNewIssueLabelContainer': string;
  'series': string;
  'seriesName': string;
}
export const cssExports: CssExports;
export default cssExports;
