// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionHeader': string;
  'clearLookupButton': string;
  'filterInput': string;
  'helpText': string;
  'issueCountHeader': string;
  'message': string;
  'nameHeader': string;
  'noResults': string;
  'posterHeader': string;
  'publisherHeader': string;
  'resultCount': string;
  'resultsTable': string;
  'searchContainer': string;
  'searchIconContainer': string;
  'searchInput': string;
  'searchResults': string;
  'sortIcon': string;
  'sortIconActive': string;
  'statusHeader': string;
  'tableContainer': string;
  'tableControls': string;
  'yearHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
