// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'message': string;
  'retagIcon': string;
  'searchForNewIssueContainer': string;
  'searchForNewIssueInput': string;
  'searchForNewIssueLabel': string;
  'searchForNewIssueLabelContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
