// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alreadyExistsIcon': string;
  'content': string;
  'icons': string;
  'mbLink': string;
  'mbLinkIcon': string;
  'metaRow': string;
  'metaSeparator': string;
  'name': string;
  'overlay': string;
  'overview': string;
  'poster': string;
  'posterContainer': string;
  'posterPlaceholder': string;
  'searchResult': string;
  'statusContinuing': string;
  'statusEnded': string;
  'underlay': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
