// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionCell': string;
  'addButton': string;
  'existingRow': string;
  'existsIcon': string;
  'externalLink': string;
  'issueCountCell': string;
  'nameCell': string;
  'posterCell': string;
  'publisherCell': string;
  'row': string;
  'seriesLink': string;
  'statusCancelled': string;
  'statusCell': string;
  'statusContinuing': string;
  'statusEnded': string;
  'statusUnknown': string;
  'thumbnail': string;
  'thumbnailPlaceholder': string;
  'yearCell': string;
}
export const cssExports: CssExports;
export default cssExports;
