// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'content': string;
  'existsBadge': string;
  'externalLink': string;
  'externalLinkIcon': string;
  'icons': string;
  'metaRow': string;
  'metaSeparator': string;
  'name': string;
  'overlay': string;
  'overview': string;
  'placeholderLetter': string;
  'poster': string;
  'posterContainer': string;
  'posterPlaceholder': string;
  'publisherBadge': string;
  'searchResult': string;
  'statusContinuing': string;
  'statusEnded': string;
  'titleRow': string;
  'typeBadge': string;
  'underlay': string;
  'volumeBadge': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
