// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsCell': string;
  'complete': string;
  'deck': string;
  'empty': string;
  'error': string;
  'hiddenFileInput': string;
  'incomplete': string;
  'report': string;
  'reportTitle': string;
  'searchInput': string;
  'searchPanel': string;
  'searchRow': string;
  'table': string;
  'unresolvedList': string;
}
export const cssExports: CssExports;
export default cssExports;
