// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsCell': string;
  'addSeriesPanel': string;
  'control': string;
  'controls': string;
  'coverage': string;
  'description': string;
  'error': string;
  'have': string;
  'header': string;
  'missing': string;
  'notInLibrary': string;
  'positionCell': string;
  'publisher': string;
  'pushFailure': string;
  'pushPanel': string;
  'pushRow': string;
  'pushSuccess': string;
  'select': string;
  'slotEditorRow': string;
  'table': string;
  'typeBadge': string;
  'unmatchedList': string;
}
export const cssExports: CssExports;
export default cssExports;
