// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentContainer': string;
  'filterIcon': string;
  'innerContentBody': string;
  'issueNavigationButton': string;
  'issueNavigationButtons': string;
  'issueUpButton': string;
  'selectedTab': string;
  'tab': string;
  'tabContent': string;
  'tabList': string;
}
export const cssExports: CssExports;
export default cssExports;
