// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'alternateTitlesIconContainer': string;
  'backdrop': string;
  'backdropOverlay': string;
  'cover': string;
  'details': string;
  'detailsLabel': string;
  'header': string;
  'headerContent': string;
  'info': string;
  'issueNumber': string;
  'links': string;
  'monitorToggleButton': string;
  'overview': string;
  'overviewExpanded': string;
  'overviewText': string;
  'overviewToggle': string;
  'publisher': string;
  'qualityProfileName': string;
  'seriesLink': string;
  'sizeOnDisk': string;
  'tags': string;
  'title': string;
  'titleContainer': string;
  'titleRow': string;
  'toggleMonitoredContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
