// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'empty': string;
  'fieldName': string;
  'fieldValue': string;
  'row': string;
  'section': string;
  'sectionHeader': string;
  'table': string;
}
export const cssExports: CssExports;
export default cssExports;
