// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'added': string;
  'bannerImage': string;
  'cell': string;
  'checkInput': string;
  'genres': string;
  'issueFileCount': string;
  'issueProgress': string;
  'link': string;
  'metadataProfileId': string;
  'overlayTitle': string;
  'path': string;
  'qualityProfileId': string;
  'ratings': string;
  'releaseDate': string;
  'seriesName': string;
  'sizeOnDisk': string;
  'status': string;
  'tags': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
