// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'counts': string;
  'empty': string;
  'grid': string;
  'name': string;
  'tile': string;
}
export const cssExports: CssExports;
export default cssExports;
