// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'added': string;
  'banner': string;
  'bannerGrow': string;
  'genres': string;
  'issueCount': string;
  'issueProgress': string;
  'lastIssue': string;
  'latestIssue': string;
  'metadataProfileId': string;
  'nextIssue': string;
  'path': string;
  'qualityProfileId': string;
  'ratings': string;
  'sizeOnDisk': string;
  'sortName': string;
  'status': string;
  'tags': string;
  'useSceneNumbering': string;
}
export const cssExports: CssExports;
export default cssExports;
