// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionsCell': string;
  'emptyWeek': string;
  'error': string;
  'grabbed': string;
  'have': string;
  'missing': string;
  'searchWeek': string;
  'seriesCell': string;
  'showPreviousWeek': string;
  'table': string;
  'thisWeek': string;
  'titleCell': string;
  'unmonitored': string;
  'unreleased': string;
  'week': string;
  'weekHeader': string;
  'weekTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
