// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absoluteIssueNumber': string;
  'downloaded': string;
  'downloading': string;
  'event': string;
  'info': string;
  'issueInfo': string;
  'issueTitle': string;
  'missing': string;
  'seriesName': string;
  'statusIcon': string;
  'unmonitored': string;
  'unreleased': string;
}
export const cssExports: CssExports;
export default cssExports;
