# Default values for panelarr Helm chart.

replicaCount: 1

image:
  repository: panelarr/panelarr
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8787

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: panelarr.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  config:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi
  comics:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteMany
    size: 50Gi
    existingClaim: ""

env:
  TZ: "Etc/UTC"
  PUID: "1000"
  PGID: "1000"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
