// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absoluteEpisodeNumber': string;
  'date': string;
  'downloaded': string;
  'downloading': string;
  'event': string;
  'eventWrapper': string;
  'issueSeparator': string;
  'issueTitle': string;
  'missing': string;
  'partial': string;
  'seasonEpisodeNumber': string;
  'seriesName': string;
  'time': string;
  'unmonitored': string;
  'unreleased': string;
}
export const cssExports: CssExports;
export default cssExports;
