// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'absoluteIssueNumber': string;
  'date': string;
  'downloaded': string;
  'downloading': string;
  'event': string;
  'eventWrapper': string;
  'issueNumber': string;
  'issueSeparator': string;
  'issueTitle': string;
  'missing': string;
  'partial': string;
  'seriesName': string;
  'time': string;
  'unmonitored': string;
  'unreleased': string;
}
export const cssExports: CssExports;
export default cssExports;
